# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |gem|
  gem.name = %q{rb-kqueue}
  gem.version = "0.2.0"

  gem.authors = ["Mathieu Arnold", "Nathan Weizenbaum"]
  gem.email = %q{mat@mat.cc nex342@gmail.com}
  gem.date = %q{2012-12-03}
  gem.description = %q{A Ruby wrapper for BSD's kqueue, using FFI}
  gem.extra_rdoc_files = %w(README.md)

  gem.files = `git ls-files`.split(/\n/)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})

  gem.homepage = %q{http://github.com/mat813/rb-kqueue}
  gem.rdoc_options = ["--charset=UTF-8"]
  gem.require_paths = ["lib"]
  gem.rubygems_version = %q{1.3.5}
  gem.summary = %q{A Ruby wrapper for BSD's kqueue, using FFI}

  gem.add_runtime_dependency(%q<ffi>, [">= 0.5.0"])
  gem.add_development_dependency(%q<yard>, [">= 0.4.0"])
end

