#!/bin/bash

RELEASES_URL="https://github.com/jekyll/jekyll/releases"
JEKYLL_VERSION="2.2.0"
JEKYLL_BUNDLE="jekyll-${JEKYLL_VERSION}.tar.gz"

wget "${RELEASES_URL}/download/v${JEKYLL_VERSION}/${JEKYLL_BUNDLE}"
tar -xzvf ${JEKYLL_BUNDLE}
